services:
  db:
    container_name: mysql_db
    image: 'mysql:latest'
    environment:
      - 'MYSQL_ROOT_PASSWORD=1234'
      - 'MYSQL_DATABASE=mydb'
      - 'MYSQL_USER=user'
      - 'MYSQL_PASSWORD=1234'
    ports:
      - '3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend-network
volumes:
  mysql_data:
networks:
  backend-network:
